os:
  - linux

sudo: false

git:
  depth: 3

cache:
  directories:
    - $HOME/.pub-cache

env:
  - FLUTTER_VERSION=stable

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

before_script:
  - cd ../
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
  - cd giffy_dialog/

script:
  - ./../flutter/bin/flutter test --no-test-assets
  - ./../flutter/bin/flutter analyze .
  - ./../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run lib/
  - ./../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run test/
  - ./../flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run example/lib/
  - ./../flutter/bin/flutter test --no-test-assets --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)