name: giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialog.
version: 1.2.0
author: Sahil Kumar <xdsahil@gmail.com>
homepage: https://github.com/xsahil03x/giffy_dialog

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.7.0
  flare_flutter: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: