name: giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialog.
version: 1.2.0
author: Sahil Kumar <xdsahil@gmail.com>
homepage: https://github.com/xsahil03x/giffy_dialog

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.6.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0

flutter: