name: giffy_dialog
homepage: https://github.com/xsahil03x/giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialogs and bottom sheets.
version: 2.3.0
repository: https://github.com/xsahil03x/giffy_dialog
issue_tracker: https://github.com/xsahil03x/giffy_dialog/issues

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.10
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

topics:
  - dialog
  - bottomsheet
  - giffy-dialog
  - rive-dialog
  - lottie-dialog

screenshots:
  - description: 'Package Demo'
    path: asset/package_demo.gif